db.hostMySQL=programacion3parcial.cwulcxw2eedn.us-east-1.rds.amazonaws.com
db.hostMSSQL=database-mssql-1inf30.cozruksjfwxd.us-east-1.rds.amazonaws.com
db.esquema=reniec?useSSL=false&allowPublicKeyRetrieval=true
db.usuario=admin
db.password=pacoflaco123
db.puertoMySQL=3306
db.puertoMSSQL=1433
db.type=mysql