db.hostMySQL=prog3-labs-1inf30.cftxszzoan2v.us-east-1.rds.amazonaws.com
db.hostMSSQL=database-mssql-1inf30.cozruksjfwxd.us-east-1.rds.amazonaws.com
db.esquema=transitsoft
db.usuario=admin
db.password=pacoflaco123
db.puertoMySQL=3306
db.puertoMSSQL=1433
db.type=mysql