//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pokesoft.pucp.edu.pe/", ConfigurationName="ServiceReference1.PokemonWS")]
    public interface PokemonWS
    {
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokesoft.pucp.edu.pe/PokemonWS/getPokemonRequest", ReplyAction="http://services.pokesoft.pucp.edu.pe/PokemonWS/getPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference1.getPokemonResponse getPokemon(ServiceReference1.getPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokesoft.pucp.edu.pe/PokemonWS/getPokemonRequest", ReplyAction="http://services.pokesoft.pucp.edu.pe/PokemonWS/getPokemonResponse")]
        System.Threading.Tasks.Task<ServiceReference1.getPokemonResponse> getPokemonAsync(ServiceReference1.getPokemonRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokesoft.pucp.edu.pe/PokemonWS/getTotalCountRequest", ReplyAction="http://services.pokesoft.pucp.edu.pe/PokemonWS/getTotalCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference1.getTotalCountResponse getTotalCount(ServiceReference1.getTotalCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokesoft.pucp.edu.pe/PokemonWS/getTotalCountRequest", ReplyAction="http://services.pokesoft.pucp.edu.pe/PokemonWS/getTotalCountResponse")]
        System.Threading.Tasks.Task<ServiceReference1.getTotalCountResponse> getTotalCountAsync(ServiceReference1.getTotalCountRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pokesoft.pucp.edu.pe/")]
    public partial class pokemon
    {
        
        private double alturaField;
        
        private string descripcionField;
        
        private string estadoEvolutivoField;
        
        private int idPokemonField;
        
        private string imagenUrlField;
        
        private string nombreField;
        
        private double pesoField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura
        {
            get
            {
                return this.alturaField;
            }
            set
            {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoEvolutivo
        {
            get
            {
                return this.estadoEvolutivoField;
            }
            set
            {
                this.estadoEvolutivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPokemon
        {
            get
            {
                return this.idPokemonField;
            }
            set
            {
                this.idPokemonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string imagenUrl
        {
            get
            {
                return this.imagenUrlField;
            }
            set
            {
                this.imagenUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double peso
        {
            get
            {
                return this.pesoField;
            }
            set
            {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPokemon", WrapperNamespace="http://services.pokesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class getPokemonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index;
        
        public getPokemonRequest()
        {
        }
        
        public getPokemonRequest(int index)
        {
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPokemonResponse", WrapperNamespace="http://services.pokesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class getPokemonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.pokemon @return;
        
        public getPokemonResponse()
        {
        }
        
        public getPokemonResponse(ServiceReference1.pokemon @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTotalCount", WrapperNamespace="http://services.pokesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class getTotalCountRequest
    {
        
        public getTotalCountRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTotalCountResponse", WrapperNamespace="http://services.pokesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class getTotalCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getTotalCountResponse()
        {
        }
        
        public getTotalCountResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PokemonWSChannel : ServiceReference1.PokemonWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PokemonWSClient : System.ServiceModel.ClientBase<ServiceReference1.PokemonWS>, ServiceReference1.PokemonWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PokemonWSClient() : 
                base(PokemonWSClient.GetDefaultBinding(), PokemonWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PokemonWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), PokemonWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getPokemonResponse ServiceReference1.PokemonWS.getPokemon(ServiceReference1.getPokemonRequest request)
        {
            return base.Channel.getPokemon(request);
        }
        
        public ServiceReference1.pokemon getPokemon(int index)
        {
            ServiceReference1.getPokemonRequest inValue = new ServiceReference1.getPokemonRequest();
            inValue.index = index;
            ServiceReference1.getPokemonResponse retVal = ((ServiceReference1.PokemonWS)(this)).getPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getPokemonResponse> ServiceReference1.PokemonWS.getPokemonAsync(ServiceReference1.getPokemonRequest request)
        {
            return base.Channel.getPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPokemonResponse> getPokemonAsync(int index)
        {
            ServiceReference1.getPokemonRequest inValue = new ServiceReference1.getPokemonRequest();
            inValue.index = index;
            return ((ServiceReference1.PokemonWS)(this)).getPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getTotalCountResponse ServiceReference1.PokemonWS.getTotalCount(ServiceReference1.getTotalCountRequest request)
        {
            return base.Channel.getTotalCount(request);
        }
        
        public int getTotalCount()
        {
            ServiceReference1.getTotalCountRequest inValue = new ServiceReference1.getTotalCountRequest();
            ServiceReference1.getTotalCountResponse retVal = ((ServiceReference1.PokemonWS)(this)).getTotalCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getTotalCountResponse> ServiceReference1.PokemonWS.getTotalCountAsync(ServiceReference1.getTotalCountRequest request)
        {
            return base.Channel.getTotalCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getTotalCountResponse> getTotalCountAsync()
        {
            ServiceReference1.getTotalCountRequest inValue = new ServiceReference1.getTotalCountRequest();
            return ((ServiceReference1.PokemonWS)(this)).getTotalCountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PokemonWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PokemonWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/pokesoft_webservices/PokemonWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PokemonWSClient.GetBindingForEndpoint(EndpointConfiguration.PokemonWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PokemonWSClient.GetEndpointAddress(EndpointConfiguration.PokemonWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PokemonWSPort,
        }
    }
}
