# ======================================================
# CONFIGURACIÓN DE BASE DE DATOS
# Reemplace o modifique y descomente estos valores con
# sus datos para que sea posible la conexión a la BD.
# ======================================================
db.hostMySQL=programacion3parcial.cwulcxw2eedn.us-east-1.rds.amazonaws.com
db.hostMSSQL = programacion3parcial.cwulcxw2eedn.us-east-1.rds.amazonaws.com
db.esquema=pokemondb
db.usuario=admin
db.password=pacoflaco123
db.puertoMySQL=3306
db.puertoMSSQL=1433
db.type=mysql