db.hostMySQL=mysql-prog3-1inf30.c8rwgfr8vu3b.us-east-1.rds.amazonaws.com
db.hostMSSQL=database-mssql-1inf30.cozruksjfwxd.us-east-1.rds.amazonaws.com
db.esquema=prog3
db.usuario=admin
db.password=1inf3020261
db.puertoMySQL=3306
db.puertoMSSQL=1433
db.type=mysql