driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
tipo_de_driver=jdbc:sqlserver
base_de_datos=transitsoft
nombre_de_host=squirlearn-mssql.ctccko4gqn7o.us-east-1.rds.amazonaws.com
puerto=1433
usuario=root
contrasenha=Jdz8vnbsdGVmFPdHIiYWrg==