# Tipo de BD: mysql o sqlserver
db.type=mysql

# Para MySQL
db.hostMySQL=localhost
db.puertoMySQL=3306
db.esquema=testsoft
db.usuario=root
db.password=pacoflaco123

# Para SQL Server
db.hostMSSQL=localhost
db.puertoMSSQL=1433
