//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", ConfigurationName="PokemonService.PokemonWS")]
    public interface PokemonWS
    {
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/listarPokemonesRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/listarPokemonesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PokemonService.listarPokemonesResponse listarPokemones(PokemonService.listarPokemonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/listarPokemonesRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/listarPokemonesResponse")]
        System.Threading.Tasks.Task<PokemonService.listarPokemonesResponse> listarPokemonesAsync(PokemonService.listarPokemonesRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/buscarPokemonPorIdRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/buscarPokemonPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PokemonService.buscarPokemonPorIdResponse buscarPokemonPorId(PokemonService.buscarPokemonPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/buscarPokemonPorIdRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/buscarPokemonPorIdResponse")]
        System.Threading.Tasks.Task<PokemonService.buscarPokemonPorIdResponse> buscarPokemonPorIdAsync(PokemonService.buscarPokemonPorIdRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/insertarPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/insertarPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PokemonService.insertarPokemonResponse insertarPokemon(PokemonService.insertarPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/insertarPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/insertarPokemonResponse")]
        System.Threading.Tasks.Task<PokemonService.insertarPokemonResponse> insertarPokemonAsync(PokemonService.insertarPokemonRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/filtrarPokemonesRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/filtrarPokemonesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PokemonService.filtrarPokemonesResponse filtrarPokemones(PokemonService.filtrarPokemonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/PokemonWS/filtrarPokemonesRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/PokemonWS/filtrarPokemonesResponse")]
        System.Threading.Tasks.Task<PokemonService.filtrarPokemonesResponse> filtrarPokemonesAsync(PokemonService.filtrarPokemonesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pokemones.pucp.edu.pe/")]
    public partial class pokemon
    {
        
        private double alturaField;
        
        private string descripcionField;
        
        private estadoEvolutivo estadoEvolutivoField;
        
        private bool estadoEvolutivoFieldSpecified;
        
        private int idPokemonField;
        
        private int idTipoPokemonField;
        
        private string nombreField;
        
        private double pesoField;
        
        private string stringTipoPokemonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura
        {
            get
            {
                return this.alturaField;
            }
            set
            {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoEvolutivo estadoEvolutivo
        {
            get
            {
                return this.estadoEvolutivoField;
            }
            set
            {
                this.estadoEvolutivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoEvolutivoSpecified
        {
            get
            {
                return this.estadoEvolutivoFieldSpecified;
            }
            set
            {
                this.estadoEvolutivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPokemon
        {
            get
            {
                return this.idPokemonField;
            }
            set
            {
                this.idPokemonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idTipoPokemon
        {
            get
            {
                return this.idTipoPokemonField;
            }
            set
            {
                this.idTipoPokemonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double peso
        {
            get
            {
                return this.pesoField;
            }
            set
            {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string stringTipoPokemon
        {
            get
            {
                return this.stringTipoPokemonField;
            }
            set
            {
                this.stringTipoPokemonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pokemones.pucp.edu.pe/")]
    public enum estadoEvolutivo
    {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        FINAL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemones", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonesRequest
    {
        
        public listarPokemonesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemonesResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PokemonService.pokemon[] @return;
        
        public listarPokemonesResponse()
        {
        }
        
        public listarPokemonesResponse(PokemonService.pokemon[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPokemonPorId", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPokemonPorIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarPokemonPorIdRequest()
        {
        }
        
        public buscarPokemonPorIdRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPokemonPorIdResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPokemonPorIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PokemonService.pokemon @return;
        
        public buscarPokemonPorIdResponse()
        {
        }
        
        public buscarPokemonPorIdResponse(PokemonService.pokemon @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemon", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PokemonService.pokemon arg0;
        
        public insertarPokemonRequest()
        {
        }
        
        public insertarPokemonRequest(PokemonService.pokemon arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemonResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPokemonResponse()
        {
        }
        
        public insertarPokemonResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarPokemones", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarPokemonesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public filtrarPokemonesRequest()
        {
        }
        
        public filtrarPokemonesRequest(string arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarPokemonesResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarPokemonesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PokemonService.pokemon[] @return;
        
        public filtrarPokemonesResponse()
        {
        }
        
        public filtrarPokemonesResponse(PokemonService.pokemon[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PokemonWSChannel : PokemonService.PokemonWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PokemonWSClient : System.ServiceModel.ClientBase<PokemonService.PokemonWS>, PokemonService.PokemonWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PokemonWSClient() : 
                base(PokemonWSClient.GetDefaultBinding(), PokemonWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PokemonWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), PokemonWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PokemonWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PokemonWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PokemonService.listarPokemonesResponse PokemonService.PokemonWS.listarPokemones(PokemonService.listarPokemonesRequest request)
        {
            return base.Channel.listarPokemones(request);
        }
        
        public PokemonService.pokemon[] listarPokemones()
        {
            PokemonService.listarPokemonesRequest inValue = new PokemonService.listarPokemonesRequest();
            PokemonService.listarPokemonesResponse retVal = ((PokemonService.PokemonWS)(this)).listarPokemones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PokemonService.listarPokemonesResponse> PokemonService.PokemonWS.listarPokemonesAsync(PokemonService.listarPokemonesRequest request)
        {
            return base.Channel.listarPokemonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PokemonService.listarPokemonesResponse> listarPokemonesAsync()
        {
            PokemonService.listarPokemonesRequest inValue = new PokemonService.listarPokemonesRequest();
            return ((PokemonService.PokemonWS)(this)).listarPokemonesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PokemonService.buscarPokemonPorIdResponse PokemonService.PokemonWS.buscarPokemonPorId(PokemonService.buscarPokemonPorIdRequest request)
        {
            return base.Channel.buscarPokemonPorId(request);
        }
        
        public PokemonService.pokemon buscarPokemonPorId(int arg0)
        {
            PokemonService.buscarPokemonPorIdRequest inValue = new PokemonService.buscarPokemonPorIdRequest();
            inValue.arg0 = arg0;
            PokemonService.buscarPokemonPorIdResponse retVal = ((PokemonService.PokemonWS)(this)).buscarPokemonPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PokemonService.buscarPokemonPorIdResponse> PokemonService.PokemonWS.buscarPokemonPorIdAsync(PokemonService.buscarPokemonPorIdRequest request)
        {
            return base.Channel.buscarPokemonPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PokemonService.buscarPokemonPorIdResponse> buscarPokemonPorIdAsync(int arg0)
        {
            PokemonService.buscarPokemonPorIdRequest inValue = new PokemonService.buscarPokemonPorIdRequest();
            inValue.arg0 = arg0;
            return ((PokemonService.PokemonWS)(this)).buscarPokemonPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PokemonService.insertarPokemonResponse PokemonService.PokemonWS.insertarPokemon(PokemonService.insertarPokemonRequest request)
        {
            return base.Channel.insertarPokemon(request);
        }
        
        public int insertarPokemon(PokemonService.pokemon arg0)
        {
            PokemonService.insertarPokemonRequest inValue = new PokemonService.insertarPokemonRequest();
            inValue.arg0 = arg0;
            PokemonService.insertarPokemonResponse retVal = ((PokemonService.PokemonWS)(this)).insertarPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PokemonService.insertarPokemonResponse> PokemonService.PokemonWS.insertarPokemonAsync(PokemonService.insertarPokemonRequest request)
        {
            return base.Channel.insertarPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<PokemonService.insertarPokemonResponse> insertarPokemonAsync(PokemonService.pokemon arg0)
        {
            PokemonService.insertarPokemonRequest inValue = new PokemonService.insertarPokemonRequest();
            inValue.arg0 = arg0;
            return ((PokemonService.PokemonWS)(this)).insertarPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PokemonService.filtrarPokemonesResponse PokemonService.PokemonWS.filtrarPokemones(PokemonService.filtrarPokemonesRequest request)
        {
            return base.Channel.filtrarPokemones(request);
        }
        
        public PokemonService.pokemon[] filtrarPokemones(string arg0, int arg1, string arg2)
        {
            PokemonService.filtrarPokemonesRequest inValue = new PokemonService.filtrarPokemonesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            PokemonService.filtrarPokemonesResponse retVal = ((PokemonService.PokemonWS)(this)).filtrarPokemones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PokemonService.filtrarPokemonesResponse> PokemonService.PokemonWS.filtrarPokemonesAsync(PokemonService.filtrarPokemonesRequest request)
        {
            return base.Channel.filtrarPokemonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PokemonService.filtrarPokemonesResponse> filtrarPokemonesAsync(string arg0, int arg1, string arg2)
        {
            PokemonService.filtrarPokemonesRequest inValue = new PokemonService.filtrarPokemonesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((PokemonService.PokemonWS)(this)).filtrarPokemonesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PokemonWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PokemonWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/PokeWS-1.0-SNAPSHOT/PokemonWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PokemonWSClient.GetBindingForEndpoint(EndpointConfiguration.PokemonWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PokemonWSClient.GetEndpointAddress(EndpointConfiguration.PokemonWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PokemonWSPort,
        }
    }
}
