# Tipo de BD: mysql o sqlserver
db.type=mysql

# Para MySQL
db.hostMySQL=prog3-labs-1inf30.cftxszzoan2v.us-east-1.rds.amazonaws.com
db.puertoMySQL=3306
db.esquema=testsoft
db.usuario=admin
db.password=labs1inf3020261

# Para SQL Server
db.hostMSSQL=localhost
db.puertoMSSQL=1433
