//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipoPokemonService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", ConfigurationName="TipoPokemonService.TipoPokemonWS")]
    public interface TipoPokemonWS
    {
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/listarTiposPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/listarTiposPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TipoPokemonService.listarTiposPokemonResponse listarTiposPokemon(TipoPokemonService.listarTiposPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/listarTiposPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/listarTiposPokemonResponse")]
        System.Threading.Tasks.Task<TipoPokemonService.listarTiposPokemonResponse> listarTiposPokemonAsync(TipoPokemonService.listarTiposPokemonRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/buscarTipoPokemonPorIdRequest" +
            "", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/buscarTipoPokemonPorIdRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TipoPokemonService.buscarTipoPokemonPorIdResponse buscarTipoPokemonPorId(TipoPokemonService.buscarTipoPokemonPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/buscarTipoPokemonPorIdRequest" +
            "", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/buscarTipoPokemonPorIdRespons" +
            "e")]
        System.Threading.Tasks.Task<TipoPokemonService.buscarTipoPokemonPorIdResponse> buscarTipoPokemonPorIdAsync(TipoPokemonService.buscarTipoPokemonPorIdRequest request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/insertarTipoPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/insertarTipoPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TipoPokemonService.insertarTipoPokemonResponse insertarTipoPokemon(TipoPokemonService.insertarTipoPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/insertarTipoPokemonRequest", ReplyAction="http://services.pokemones.pucp.edu.pe/TipoPokemonWS/insertarTipoPokemonResponse")]
        System.Threading.Tasks.Task<TipoPokemonService.insertarTipoPokemonResponse> insertarTipoPokemonAsync(TipoPokemonService.insertarTipoPokemonRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pokemones.pucp.edu.pe/")]
    public partial class tipoPokemon
    {
        
        private int idTipoPokemonField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoPokemon
        {
            get
            {
                return this.idTipoPokemonField;
            }
            set
            {
                this.idTipoPokemonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposPokemon", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposPokemonRequest
    {
        
        public listarTiposPokemonRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposPokemonResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposPokemonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoPokemonService.tipoPokemon[] @return;
        
        public listarTiposPokemonResponse()
        {
        }
        
        public listarTiposPokemonResponse(TipoPokemonService.tipoPokemon[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarTipoPokemonPorId", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarTipoPokemonPorIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarTipoPokemonPorIdRequest()
        {
        }
        
        public buscarTipoPokemonPorIdRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarTipoPokemonPorIdResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarTipoPokemonPorIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoPokemonService.tipoPokemon @return;
        
        public buscarTipoPokemonPorIdResponse()
        {
        }
        
        public buscarTipoPokemonPorIdResponse(TipoPokemonService.tipoPokemon @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoPokemon", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoPokemonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoPokemonService.tipoPokemon arg0;
        
        public insertarTipoPokemonRequest()
        {
        }
        
        public insertarTipoPokemonRequest(TipoPokemonService.tipoPokemon arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoPokemonResponse", WrapperNamespace="http://services.pokemones.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoPokemonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pokemones.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoPokemonResponse()
        {
        }
        
        public insertarTipoPokemonResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TipoPokemonWSChannel : TipoPokemonService.TipoPokemonWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TipoPokemonWSClient : System.ServiceModel.ClientBase<TipoPokemonService.TipoPokemonWS>, TipoPokemonService.TipoPokemonWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TipoPokemonWSClient() : 
                base(TipoPokemonWSClient.GetDefaultBinding(), TipoPokemonWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TipoPokemonWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoPokemonWSClient(EndpointConfiguration endpointConfiguration) : 
                base(TipoPokemonWSClient.GetBindingForEndpoint(endpointConfiguration), TipoPokemonWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoPokemonWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TipoPokemonWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoPokemonWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TipoPokemonWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoPokemonWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TipoPokemonService.listarTiposPokemonResponse TipoPokemonService.TipoPokemonWS.listarTiposPokemon(TipoPokemonService.listarTiposPokemonRequest request)
        {
            return base.Channel.listarTiposPokemon(request);
        }
        
        public TipoPokemonService.tipoPokemon[] listarTiposPokemon()
        {
            TipoPokemonService.listarTiposPokemonRequest inValue = new TipoPokemonService.listarTiposPokemonRequest();
            TipoPokemonService.listarTiposPokemonResponse retVal = ((TipoPokemonService.TipoPokemonWS)(this)).listarTiposPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoPokemonService.listarTiposPokemonResponse> TipoPokemonService.TipoPokemonWS.listarTiposPokemonAsync(TipoPokemonService.listarTiposPokemonRequest request)
        {
            return base.Channel.listarTiposPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoPokemonService.listarTiposPokemonResponse> listarTiposPokemonAsync()
        {
            TipoPokemonService.listarTiposPokemonRequest inValue = new TipoPokemonService.listarTiposPokemonRequest();
            return ((TipoPokemonService.TipoPokemonWS)(this)).listarTiposPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TipoPokemonService.buscarTipoPokemonPorIdResponse TipoPokemonService.TipoPokemonWS.buscarTipoPokemonPorId(TipoPokemonService.buscarTipoPokemonPorIdRequest request)
        {
            return base.Channel.buscarTipoPokemonPorId(request);
        }
        
        public TipoPokemonService.tipoPokemon buscarTipoPokemonPorId(int arg0)
        {
            TipoPokemonService.buscarTipoPokemonPorIdRequest inValue = new TipoPokemonService.buscarTipoPokemonPorIdRequest();
            inValue.arg0 = arg0;
            TipoPokemonService.buscarTipoPokemonPorIdResponse retVal = ((TipoPokemonService.TipoPokemonWS)(this)).buscarTipoPokemonPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoPokemonService.buscarTipoPokemonPorIdResponse> TipoPokemonService.TipoPokemonWS.buscarTipoPokemonPorIdAsync(TipoPokemonService.buscarTipoPokemonPorIdRequest request)
        {
            return base.Channel.buscarTipoPokemonPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoPokemonService.buscarTipoPokemonPorIdResponse> buscarTipoPokemonPorIdAsync(int arg0)
        {
            TipoPokemonService.buscarTipoPokemonPorIdRequest inValue = new TipoPokemonService.buscarTipoPokemonPorIdRequest();
            inValue.arg0 = arg0;
            return ((TipoPokemonService.TipoPokemonWS)(this)).buscarTipoPokemonPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TipoPokemonService.insertarTipoPokemonResponse TipoPokemonService.TipoPokemonWS.insertarTipoPokemon(TipoPokemonService.insertarTipoPokemonRequest request)
        {
            return base.Channel.insertarTipoPokemon(request);
        }
        
        public int insertarTipoPokemon(TipoPokemonService.tipoPokemon arg0)
        {
            TipoPokemonService.insertarTipoPokemonRequest inValue = new TipoPokemonService.insertarTipoPokemonRequest();
            inValue.arg0 = arg0;
            TipoPokemonService.insertarTipoPokemonResponse retVal = ((TipoPokemonService.TipoPokemonWS)(this)).insertarTipoPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoPokemonService.insertarTipoPokemonResponse> TipoPokemonService.TipoPokemonWS.insertarTipoPokemonAsync(TipoPokemonService.insertarTipoPokemonRequest request)
        {
            return base.Channel.insertarTipoPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoPokemonService.insertarTipoPokemonResponse> insertarTipoPokemonAsync(TipoPokemonService.tipoPokemon arg0)
        {
            TipoPokemonService.insertarTipoPokemonRequest inValue = new TipoPokemonService.insertarTipoPokemonRequest();
            inValue.arg0 = arg0;
            return ((TipoPokemonService.TipoPokemonWS)(this)).insertarTipoPokemonAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoPokemonWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoPokemonWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/PokeWS-1.0-SNAPSHOT/TipoPokemonWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TipoPokemonWSClient.GetBindingForEndpoint(EndpointConfiguration.TipoPokemonWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TipoPokemonWSClient.GetEndpointAddress(EndpointConfiguration.TipoPokemonWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TipoPokemonWSPort,
        }
    }
}
