USE schemaCaso2;
DELIMITER $$

DROP PROCEDURE IF EXISTS INSERTAR_FACULTAD$$
DROP PROCEDURE IF EXISTS MODIFICAR_FACULTAD$$
DROP PROCEDURE IF EXISTS ELIMINAR_FACULTAD$$
DROP PROCEDURE IF EXISTS OBTENER_FACULTAD_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_FACULTADS$$
DROP PROCEDURE IF EXISTS INSERTAR_DEPARTAMENTO$$
DROP PROCEDURE IF EXISTS MODIFICAR_DEPARTAMENTO$$
DROP PROCEDURE IF EXISTS ELIMINAR_DEPARTAMENTO$$
DROP PROCEDURE IF EXISTS OBTENER_DEPARTAMENTO_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_DEPARTAMENTOS$$
DROP PROCEDURE IF EXISTS INSERTAR_ESPECIALIDAD$$
DROP PROCEDURE IF EXISTS MODIFICAR_ESPECIALIDAD$$
DROP PROCEDURE IF EXISTS ELIMINAR_ESPECIALIDAD$$
DROP PROCEDURE IF EXISTS OBTENER_ESPECIALIDAD_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_ESPECIALIDADS$$
DROP PROCEDURE IF EXISTS INSERTAR_DOCENTE$$
DROP PROCEDURE IF EXISTS MODIFICAR_DOCENTE$$
DROP PROCEDURE IF EXISTS ELIMINAR_DOCENTE$$
DROP PROCEDURE IF EXISTS OBTENER_DOCENTE_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_DOCENTES$$
DROP PROCEDURE IF EXISTS INSERTAR_CURSO$$
DROP PROCEDURE IF EXISTS MODIFICAR_CURSO$$
DROP PROCEDURE IF EXISTS ELIMINAR_CURSO$$
DROP PROCEDURE IF EXISTS OBTENER_CURSO_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_CURSOS$$
DROP PROCEDURE IF EXISTS INSERTAR_ESTUDIANTE$$
DROP PROCEDURE IF EXISTS MODIFICAR_ESTUDIANTE$$
DROP PROCEDURE IF EXISTS ELIMINAR_ESTUDIANTE$$
DROP PROCEDURE IF EXISTS OBTENER_ESTUDIANTE_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_ESTUDIANTES$$
DROP PROCEDURE IF EXISTS INSERTAR_AULA$$
DROP PROCEDURE IF EXISTS MODIFICAR_AULA$$
DROP PROCEDURE IF EXISTS ELIMINAR_AULA$$
DROP PROCEDURE IF EXISTS OBTENER_AULA_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_AULAS$$
DROP PROCEDURE IF EXISTS INSERTAR_HORARIO_CURSO$$
DROP PROCEDURE IF EXISTS MODIFICAR_HORARIO_CURSO$$
DROP PROCEDURE IF EXISTS ELIMINAR_HORARIO_CURSO$$
DROP PROCEDURE IF EXISTS OBTENER_HORARIO_CURSO_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_HORARIO_CURSOS$$
DROP PROCEDURE IF EXISTS INSERTAR_HORARIO_CURSO_DET$$
DROP PROCEDURE IF EXISTS MODIFICAR_HORARIO_CURSO_DET$$
DROP PROCEDURE IF EXISTS ELIMINAR_HORARIO_CURSO_DET$$
DROP PROCEDURE IF EXISTS OBTENER_HORARIO_CURSO_DET_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_HORARIO_CURSO_DETS$$
DROP PROCEDURE IF EXISTS INSERTAR_MATRICULA$$
DROP PROCEDURE IF EXISTS MODIFICAR_MATRICULA$$
DROP PROCEDURE IF EXISTS ELIMINAR_MATRICULA$$
DROP PROCEDURE IF EXISTS OBTENER_MATRICULA_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_MATRICULAS$$
DROP PROCEDURE IF EXISTS INSERTAR_EVALUACION$$
DROP PROCEDURE IF EXISTS MODIFICAR_EVALUACION$$
DROP PROCEDURE IF EXISTS ELIMINAR_EVALUACION$$
DROP PROCEDURE IF EXISTS OBTENER_EVALUACION_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_EVALUACIONS$$
DROP PROCEDURE IF EXISTS INSERTAR_NOTA$$
DROP PROCEDURE IF EXISTS MODIFICAR_NOTA$$
DROP PROCEDURE IF EXISTS ELIMINAR_NOTA$$
DROP PROCEDURE IF EXISTS OBTENER_NOTA_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_NOTAS$$
DROP PROCEDURE IF EXISTS INSERTAR_CURSO_PRERREQUISITO$$
DROP PROCEDURE IF EXISTS MODIFICAR_CURSO_PRERREQUISITO$$
DROP PROCEDURE IF EXISTS ELIMINAR_CURSO_PRERREQUISITO$$
DROP PROCEDURE IF EXISTS OBTENER_CURSO_PRERREQUISITO_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_CURSOS_PRERREQUISITOS$$
DROP PROCEDURE IF EXISTS INSERTAR_MATRICULA_HORARIO$$
DROP PROCEDURE IF EXISTS MODIFICAR_MATRICULA_HORARIO$$
DROP PROCEDURE IF EXISTS ELIMINAR_MATRICULA_HORARIO$$
DROP PROCEDURE IF EXISTS OBTENER_MATRICULA_HORARIO_X_ID$$
DROP PROCEDURE IF EXISTS LISTAR_MATRICULAS_HORARIOS$$
DROP PROCEDURE IF EXISTS CONTAR_MATRICULADOS_HORARIO$$
DROP PROCEDURE IF EXISTS EXISTE_CONFLICTO_HORARIO$$
DROP PROCEDURE IF EXISTS REGISTRAR_MATRICULA_HORARIO_VALIDADO$$
DROP PROCEDURE IF EXISTS CALCULAR_PROMEDIO_FINAL$$

CREATE PROCEDURE INSERTAR_FACULTAD(
    INOUT p_facultad_id BIGINT UNSIGNED, IN p_nombre VARCHAR(100), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_FACULTADES (FACULTAD_ID, NOMBRE, ACTIVO)
    VALUES (p_facultad_id, p_nombre, p_activo);
END$$

CREATE PROCEDURE MODIFICAR_FACULTAD(
    IN p_facultad_id BIGINT UNSIGNED, IN p_nombre VARCHAR(100), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_FACULTADES
    SET NOMBRE = p_nombre,
        ACTIVO = p_activo
    WHERE FACULTAD_ID = p_facultad_id;
END$$

CREATE PROCEDURE ELIMINAR_FACULTAD(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_FACULTADES SET ACTIVO = 0 WHERE FACULTAD_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_FACULTAD_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_FACULTADES
    WHERE FACULTAD_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_FACULTADS()
BEGIN
    SELECT * FROM UNI_FACULTADES WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_DEPARTAMENTO(
    INOUT p_departamento_id BIGINT UNSIGNED, IN p_nombre VARCHAR(120), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_DEPARTAMENTOS (DEPARTAMENTO_ID, NOMBRE, ACTIVO)
    VALUES (p_departamento_id, p_nombre, p_activo);
END$$

CREATE PROCEDURE MODIFICAR_DEPARTAMENTO(
    IN p_departamento_id BIGINT UNSIGNED, IN p_nombre VARCHAR(120), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_DEPARTAMENTOS
    SET NOMBRE = p_nombre,
        ACTIVO = p_activo
    WHERE DEPARTAMENTO_ID = p_departamento_id;
END$$

CREATE PROCEDURE ELIMINAR_DEPARTAMENTO(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_DEPARTAMENTOS SET ACTIVO = 0 WHERE DEPARTAMENTO_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_DEPARTAMENTO_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_DEPARTAMENTOS
    WHERE DEPARTAMENTO_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_DEPARTAMENTOS()
BEGIN
    SELECT * FROM UNI_DEPARTAMENTOS WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_ESPECIALIDAD(
    INOUT p_especialidad_id BIGINT UNSIGNED, IN p_facultad_id BIGINT UNSIGNED, IN p_nombre VARCHAR(100), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_ESPECIALIDADES (ESPECIALIDAD_ID, FACULTAD_ID, NOMBRE, ACTIVO)
    VALUES (p_especialidad_id, p_facultad_id, p_nombre, p_activo);
END$$

CREATE PROCEDURE MODIFICAR_ESPECIALIDAD(
    IN p_especialidad_id BIGINT UNSIGNED, IN p_facultad_id BIGINT UNSIGNED, IN p_nombre VARCHAR(100), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_ESPECIALIDADES
    SET FACULTAD_ID = p_facultad_id,
        NOMBRE = p_nombre,
        ACTIVO = p_activo
    WHERE ESPECIALIDAD_ID = p_especialidad_id;
END$$

CREATE PROCEDURE ELIMINAR_ESPECIALIDAD(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_ESPECIALIDADES SET ACTIVO = 0 WHERE ESPECIALIDAD_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_ESPECIALIDAD_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_ESPECIALIDADES
    WHERE ESPECIALIDAD_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_ESPECIALIDADS()
BEGIN
    SELECT * FROM UNI_ESPECIALIDADES WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_DOCENTE(
    INOUT p_docente_id BIGINT UNSIGNED, IN p_departamento_id BIGINT UNSIGNED, IN p_codigo VARCHAR(20), IN p_nombre_completo VARCHAR(150), IN p_categoria VARCHAR(30), IN p_dedicacion VARCHAR(20), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_DOCENTES (DEPARTAMENTO_ID, CODIGO, NOMBRE_COMPLETO, CATEGORIA, DEDICACION, ACTIVO)
    VALUES (p_departamento_id, p_codigo, p_nombre_completo, p_categoria, p_dedicacion, p_activo);
    SET p_docente_id = LAST_INSERT_ID();
END$$

CREATE PROCEDURE MODIFICAR_DOCENTE(
    IN p_docente_id BIGINT UNSIGNED, IN p_departamento_id BIGINT UNSIGNED, IN p_codigo VARCHAR(20), IN p_nombre_completo VARCHAR(150), IN p_categoria VARCHAR(30), IN p_dedicacion VARCHAR(20), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_DOCENTES
    SET DEPARTAMENTO_ID = p_departamento_id,
        CODIGO = p_codigo,
        NOMBRE_COMPLETO = p_nombre_completo,
        CATEGORIA = p_categoria,
        DEDICACION = p_dedicacion,
        ACTIVO = p_activo
    WHERE DOCENTE_ID = p_docente_id;
END$$

CREATE PROCEDURE ELIMINAR_DOCENTE(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_DOCENTES SET ACTIVO = 0 WHERE DOCENTE_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_DOCENTE_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_DOCENTES
    WHERE DOCENTE_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_DOCENTES()
BEGIN
    SELECT * FROM UNI_DOCENTES WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_CURSO(
    INOUT p_curso_id BIGINT UNSIGNED, IN p_especialidad_id BIGINT UNSIGNED, IN p_codigo VARCHAR(20), IN p_nombre VARCHAR(150), IN p_creditos TINYINT UNSIGNED, IN p_nivel_academico TINYINT UNSIGNED, IN p_estado_curso VARCHAR(15), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_CURSOS (CURSO_ID, ESPECIALIDAD_ID, CODIGO, NOMBRE, CREDITOS, NIVEL_ACADEMICO, ESTADO_CURSO, ACTIVO)
    VALUES (p_curso_id, p_especialidad_id, p_codigo, p_nombre, p_creditos, p_nivel_academico, p_estado_curso, p_activo);
END$$

CREATE PROCEDURE MODIFICAR_CURSO(
    IN p_curso_id BIGINT UNSIGNED, IN p_especialidad_id BIGINT UNSIGNED, IN p_codigo VARCHAR(20), IN p_nombre VARCHAR(150), IN p_creditos TINYINT UNSIGNED, IN p_nivel_academico TINYINT UNSIGNED, IN p_estado_curso VARCHAR(15), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_CURSOS
    SET ESPECIALIDAD_ID = p_especialidad_id,
        CODIGO = p_codigo,
        NOMBRE = p_nombre,
        CREDITOS = p_creditos,
        NIVEL_ACADEMICO = p_nivel_academico,
        ESTADO_CURSO = p_estado_curso,
        ACTIVO = p_activo
    WHERE CURSO_ID = p_curso_id;
END$$

CREATE PROCEDURE ELIMINAR_CURSO(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_CURSOS SET ACTIVO = 0 WHERE CURSO_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_CURSO_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_CURSOS
    WHERE CURSO_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_CURSOS()
BEGIN
    SELECT * FROM UNI_CURSOS WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_ESTUDIANTE(
    INOUT p_estudiante_id BIGINT UNSIGNED, IN p_especialidad_id BIGINT UNSIGNED, IN p_codigo_universitario VARCHAR(20), IN p_nombres VARCHAR(80), IN p_apellidos VARCHAR(80), IN p_correo_institucional VARCHAR(120), IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_ESTUDIANTES (ESPECIALIDAD_ID, CODIGO_UNIVERSITARIO, NOMBRES, APELLIDOS, CORREO_INSTITUCIONAL, ACTIVO)
    VALUES (p_especialidad_id, p_codigo_universitario, p_nombres, p_apellidos, p_correo_institucional, p_activo);
    SET p_estudiante_id = LAST_INSERT_ID();
END$$

CREATE PROCEDURE MODIFICAR_ESTUDIANTE(
    IN p_estudiante_id BIGINT UNSIGNED, IN p_especialidad_id BIGINT UNSIGNED, IN p_codigo_universitario VARCHAR(20), IN p_nombres VARCHAR(80), IN p_apellidos VARCHAR(80), IN p_correo_institucional VARCHAR(120), IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_ESTUDIANTES
    SET ESPECIALIDAD_ID = p_especialidad_id,
        CODIGO_UNIVERSITARIO = p_codigo_universitario,
        NOMBRES = p_nombres,
        APELLIDOS = p_apellidos,
        CORREO_INSTITUCIONAL = p_correo_institucional,
        ACTIVO = p_activo
    WHERE ESTUDIANTE_ID = p_estudiante_id;
END$$

CREATE PROCEDURE ELIMINAR_ESTUDIANTE(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_ESTUDIANTES SET ACTIVO = 0 WHERE ESTUDIANTE_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_ESTUDIANTE_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_ESTUDIANTES
    WHERE ESTUDIANTE_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_ESTUDIANTES()
BEGIN
    SELECT * FROM UNI_ESTUDIANTES WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_AULA(
    INOUT p_aula_id BIGINT UNSIGNED, IN p_uni_codigo_aula VARCHAR(20), IN p_uni_ubicacion VARCHAR(120), IN p_uni_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_AULAS (AULA_ID, UNI_CODIGO_AULA, UNI_UBICACION, UNI_ACTIVO)
    VALUES (p_aula_id, p_uni_codigo_aula, p_uni_ubicacion, p_uni_activo);
END$$

CREATE PROCEDURE MODIFICAR_AULA(
    IN p_aula_id BIGINT UNSIGNED, IN p_uni_codigo_aula VARCHAR(20), IN p_uni_ubicacion VARCHAR(120), IN p_uni_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_AULAS
    SET UNI_CODIGO_AULA = p_uni_codigo_aula,
        UNI_UBICACION = p_uni_ubicacion,
        UNI_ACTIVO = p_uni_activo
    WHERE AULA_ID = p_aula_id;
END$$

CREATE PROCEDURE ELIMINAR_AULA(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_AULAS SET UNI_ACTIVO = 0 WHERE AULA_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_AULA_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_AULAS
    WHERE AULA_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_AULAS()
BEGIN
    SELECT * FROM UNI_AULAS WHERE UNI_ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_HORARIO_CURSO(
    INOUT p_horario_curso_id BIGINT UNSIGNED, IN p_curso_id BIGINT UNSIGNED, IN p_semestre VARCHAR(10), IN p_codigo_horario VARCHAR(10), IN p_docente_id BIGINT UNSIGNED, IN p_cupo_maximo SMALLINT UNSIGNED, IN p_estado VARCHAR(15)
)
BEGIN
    INSERT INTO UNI_HORARIOS_CURSO (HORARIO_CURSO_ID, CURSO_ID, SEMESTRE, CODIGO_HORARIO, DOCENTE_ID, CUPO_MAXIMO, ESTADO)
    VALUES (p_horario_curso_id, p_curso_id, p_semestre, p_codigo_horario, p_docente_id, p_cupo_maximo, p_estado);
END$$

CREATE PROCEDURE MODIFICAR_HORARIO_CURSO(
    IN p_horario_curso_id BIGINT UNSIGNED, IN p_curso_id BIGINT UNSIGNED, IN p_semestre VARCHAR(10), IN p_codigo_horario VARCHAR(10), IN p_docente_id BIGINT UNSIGNED, IN p_cupo_maximo SMALLINT UNSIGNED, IN p_estado VARCHAR(15)
)
BEGIN
    UPDATE UNI_HORARIOS_CURSO
    SET CURSO_ID = p_curso_id,
        SEMESTRE = p_semestre,
        CODIGO_HORARIO = p_codigo_horario,
        DOCENTE_ID = p_docente_id,
        CUPO_MAXIMO = p_cupo_maximo,
        ESTADO = p_estado
    WHERE HORARIO_CURSO_ID = p_horario_curso_id;
END$$

CREATE PROCEDURE ELIMINAR_HORARIO_CURSO(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_HORARIOS_CURSO WHERE HORARIO_CURSO_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_HORARIO_CURSO_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_HORARIOS_CURSO
    WHERE HORARIO_CURSO_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_HORARIO_CURSOS()
BEGIN
    SELECT * FROM UNI_HORARIOS_CURSO;
END$$

CREATE PROCEDURE INSERTAR_HORARIO_CURSO_DET(
    INOUT p_horario_curso_det_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_tipo_sesion VARCHAR(15), IN p_dia_semana TINYINT UNSIGNED, IN p_hora_inicio DATETIME, IN p_hora_fin DATETIME, IN p_aula_id BIGINT UNSIGNED, IN p_frecuencia VARCHAR(15)
)
BEGIN
    INSERT INTO UNI_HORARIOS_CURSO_DET (HORARIO_CURSO_DET_ID, HORARIO_CURSO_ID, TIPO_SESION, DIA_SEMANA, HORA_INICIO, HORA_FIN, AULA_ID, FRECUENCIA)
    VALUES (p_horario_curso_det_id, p_horario_curso_id, p_tipo_sesion, p_dia_semana, p_hora_inicio, p_hora_fin, p_aula_id, p_frecuencia);
END$$

CREATE PROCEDURE MODIFICAR_HORARIO_CURSO_DET(
    IN p_horario_curso_det_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_tipo_sesion VARCHAR(15), IN p_dia_semana TINYINT UNSIGNED, IN p_hora_inicio DATETIME, IN p_hora_fin DATETIME, IN p_aula_id BIGINT UNSIGNED, IN p_frecuencia VARCHAR(15)
)
BEGIN
    UPDATE UNI_HORARIOS_CURSO_DET
    SET HORARIO_CURSO_ID = p_horario_curso_id,
        TIPO_SESION = p_tipo_sesion,
        DIA_SEMANA = p_dia_semana,
        HORA_INICIO = p_hora_inicio,
        HORA_FIN = p_hora_fin,
        AULA_ID = p_aula_id,
        FRECUENCIA = p_frecuencia
    WHERE HORARIO_CURSO_DET_ID = p_horario_curso_det_id;
END$$

CREATE PROCEDURE ELIMINAR_HORARIO_CURSO_DET(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_HORARIOS_CURSO_DET WHERE HORARIO_CURSO_DET_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_HORARIO_CURSO_DET_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_HORARIOS_CURSO_DET
    WHERE HORARIO_CURSO_DET_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_HORARIO_CURSO_DETS()
BEGIN
    SELECT * FROM UNI_HORARIOS_CURSO_DET;
END$$

CREATE PROCEDURE INSERTAR_MATRICULA(
    INOUT p_matricula_id BIGINT UNSIGNED, IN p_estudiante_id BIGINT UNSIGNED, IN p_semestre VARCHAR(10), IN p_fecha_inscripcion DATETIME, IN p_tipo_matricula VARCHAR(15), IN p_estado_matricula VARCHAR(15), IN p_modalidad VARCHAR(15)
)
BEGIN
    INSERT INTO UNI_MATRICULAS (ESTUDIANTE_ID, SEMESTRE, FECHA_INSCRIPCION, TIPO_MATRICULA, ESTADO_MATRICULA, MODALIDAD)
    VALUES (p_estudiante_id, p_semestre, p_fecha_inscripcion, p_tipo_matricula, p_estado_matricula, p_modalidad);
    SET p_matricula_id = LAST_INSERT_ID();
END$$

CREATE PROCEDURE MODIFICAR_MATRICULA(
    IN p_matricula_id BIGINT UNSIGNED, IN p_estudiante_id BIGINT UNSIGNED, IN p_semestre VARCHAR(10), IN p_fecha_inscripcion DATETIME, IN p_tipo_matricula VARCHAR(15), IN p_estado_matricula VARCHAR(15), IN p_modalidad VARCHAR(15)
)
BEGIN
    UPDATE UNI_MATRICULAS
    SET ESTUDIANTE_ID = p_estudiante_id,
        SEMESTRE = p_semestre,
        FECHA_INSCRIPCION = p_fecha_inscripcion,
        TIPO_MATRICULA = p_tipo_matricula,
        ESTADO_MATRICULA = p_estado_matricula,
        MODALIDAD = p_modalidad
    WHERE MATRICULA_ID = p_matricula_id;
END$$

CREATE PROCEDURE ELIMINAR_MATRICULA(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_MATRICULAS WHERE MATRICULA_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_MATRICULA_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_MATRICULAS
    WHERE MATRICULA_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_MATRICULAS()
BEGIN
    SELECT * FROM UNI_MATRICULAS;
END$$

CREATE PROCEDURE INSERTAR_EVALUACION(
    INOUT p_evaluacion_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_tipo_evaluacion VARCHAR(15), IN p_peso DECIMAL(5,2), IN p_fecha_evaluacion DATETIME
)
BEGIN
    INSERT INTO UNI_EVALUACIONES (EVALUACION_ID, HORARIO_CURSO_ID, TIPO_EVALUACION, PESO, FECHA_EVALUACION)
    VALUES (p_evaluacion_id, p_horario_curso_id, p_tipo_evaluacion, p_peso, p_fecha_evaluacion);
END$$

CREATE PROCEDURE MODIFICAR_EVALUACION(
    IN p_evaluacion_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_tipo_evaluacion VARCHAR(15), IN p_peso DECIMAL(5,2), IN p_fecha_evaluacion DATETIME
)
BEGIN
    UPDATE UNI_EVALUACIONES
    SET HORARIO_CURSO_ID = p_horario_curso_id,
        TIPO_EVALUACION = p_tipo_evaluacion,
        PESO = p_peso,
        FECHA_EVALUACION = p_fecha_evaluacion
    WHERE EVALUACION_ID = p_evaluacion_id;
END$$

CREATE PROCEDURE ELIMINAR_EVALUACION(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_EVALUACIONES WHERE EVALUACION_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_EVALUACION_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_EVALUACIONES
    WHERE EVALUACION_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_EVALUACIONS()
BEGIN
    SELECT * FROM UNI_EVALUACIONES;
END$$

CREATE PROCEDURE INSERTAR_NOTA(
    INOUT p_nota_id BIGINT UNSIGNED, IN p_evaluacion_id BIGINT UNSIGNED, IN p_matricula_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_calificacion DECIMAL(5,2)
)
BEGIN
    INSERT INTO UNI_NOTAS (NOTA_ID, EVALUACION_ID, MATRICULA_ID, HORARIO_CURSO_ID, CALIFICACION)
    VALUES (p_nota_id, p_evaluacion_id, p_matricula_id, p_horario_curso_id, p_calificacion);
END$$

CREATE PROCEDURE MODIFICAR_NOTA(
    IN p_nota_id BIGINT UNSIGNED, IN p_evaluacion_id BIGINT UNSIGNED, IN p_matricula_id BIGINT UNSIGNED, IN p_horario_curso_id BIGINT UNSIGNED, IN p_calificacion DECIMAL(5,2)
)
BEGIN
    UPDATE UNI_NOTAS
    SET EVALUACION_ID = p_evaluacion_id,
        MATRICULA_ID = p_matricula_id,
        HORARIO_CURSO_ID = p_horario_curso_id,
        CALIFICACION = p_calificacion
    WHERE NOTA_ID = p_nota_id;
END$$

CREATE PROCEDURE ELIMINAR_NOTA(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_NOTAS WHERE NOTA_ID = p_id;
END$$

CREATE PROCEDURE OBTENER_NOTA_X_ID(
    IN p_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_NOTAS
    WHERE NOTA_ID = p_id;
END$$

CREATE PROCEDURE LISTAR_NOTAS()
BEGIN
    SELECT * FROM UNI_NOTAS;
END$$

CREATE PROCEDURE INSERTAR_CURSO_PRERREQUISITO(
    IN p_curso_id BIGINT UNSIGNED,
    IN p_curso_prerreq_id BIGINT UNSIGNED,
    IN p_activo TINYINT UNSIGNED
)
BEGIN
    INSERT INTO UNI_CURSOS_PRERREQUISITOS (CURSO_ID, CURSO_PRERREQ_ID, ACTIVO)
    VALUES (p_curso_id, p_curso_prerreq_id, p_activo);
END$$

CREATE PROCEDURE MODIFICAR_CURSO_PRERREQUISITO(
    IN p_curso_id BIGINT UNSIGNED,
    IN p_curso_prerreq_id BIGINT UNSIGNED,
    IN p_activo TINYINT UNSIGNED
)
BEGIN
    UPDATE UNI_CURSOS_PRERREQUISITOS
    SET ACTIVO = p_activo
    WHERE CURSO_ID = p_curso_id
      AND CURSO_PRERREQ_ID = p_curso_prerreq_id;
END$$

CREATE PROCEDURE ELIMINAR_CURSO_PRERREQUISITO(
    IN p_curso_id BIGINT UNSIGNED,
    IN p_curso_prerreq_id BIGINT UNSIGNED
)
BEGIN
    UPDATE UNI_CURSOS_PRERREQUISITOS
    SET ACTIVO = 0
    WHERE CURSO_ID = p_curso_id
      AND CURSO_PRERREQ_ID = p_curso_prerreq_id;
END$$

CREATE PROCEDURE OBTENER_CURSO_PRERREQUISITO_X_ID(
    IN p_curso_id BIGINT UNSIGNED,
    IN p_curso_prerreq_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_CURSOS_PRERREQUISITOS
    WHERE CURSO_ID = p_curso_id
      AND CURSO_PRERREQ_ID = p_curso_prerreq_id;
END$$

CREATE PROCEDURE LISTAR_CURSOS_PRERREQUISITOS()
BEGIN
    SELECT * FROM UNI_CURSOS_PRERREQUISITOS
    WHERE ACTIVO = 1;
END$$

CREATE PROCEDURE INSERTAR_MATRICULA_HORARIO(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED,
    IN p_fecha_registro DATETIME
)
BEGIN
    INSERT INTO UNI_MATRICULAS_HORARIOS (MATRICULA_ID, HORARIO_CURSO_ID, FECHA_REGISTRO)
    VALUES (p_matricula_id, p_horario_curso_id, COALESCE(p_fecha_registro, CURRENT_TIMESTAMP));
END$$

CREATE PROCEDURE MODIFICAR_MATRICULA_HORARIO(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED,
    IN p_fecha_registro DATETIME
)
BEGIN
    UPDATE UNI_MATRICULAS_HORARIOS
    SET FECHA_REGISTRO = COALESCE(p_fecha_registro, FECHA_REGISTRO)
    WHERE MATRICULA_ID = p_matricula_id
      AND HORARIO_CURSO_ID = p_horario_curso_id;
END$$

CREATE PROCEDURE ELIMINAR_MATRICULA_HORARIO(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED
)
BEGIN
    DELETE FROM UNI_MATRICULAS_HORARIOS
    WHERE MATRICULA_ID = p_matricula_id
      AND HORARIO_CURSO_ID = p_horario_curso_id;
END$$

CREATE PROCEDURE OBTENER_MATRICULA_HORARIO_X_ID(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED
)
BEGIN
    SELECT * FROM UNI_MATRICULAS_HORARIOS
    WHERE MATRICULA_ID = p_matricula_id
      AND HORARIO_CURSO_ID = p_horario_curso_id;
END$$

CREATE PROCEDURE LISTAR_MATRICULAS_HORARIOS()
BEGIN
    SELECT * FROM UNI_MATRICULAS_HORARIOS;
END$$

CREATE PROCEDURE CONTAR_MATRICULADOS_HORARIO(
    IN p_horario_curso_id BIGINT UNSIGNED,
    OUT p_total INT
)
BEGIN
    SELECT COUNT(*)
    INTO p_total
    FROM UNI_MATRICULAS_HORARIOS
    WHERE HORARIO_CURSO_ID = p_horario_curso_id;
END$$

CREATE PROCEDURE EXISTE_CONFLICTO_HORARIO(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED,
    OUT p_existe INT
)
BEGIN
    SELECT COUNT(*)
    INTO p_existe
    FROM UNI_MATRICULAS_HORARIOS mh
    INNER JOIN UNI_HORARIOS_CURSO_DET det_existente
        ON det_existente.HORARIO_CURSO_ID = mh.HORARIO_CURSO_ID
    INNER JOIN UNI_HORARIOS_CURSO_DET det_nuevo
        ON det_nuevo.HORARIO_CURSO_ID = p_horario_curso_id
       AND det_nuevo.DIA_SEMANA = det_existente.DIA_SEMANA
       AND det_nuevo.HORA_INICIO < det_existente.HORA_FIN
       AND det_nuevo.HORA_FIN > det_existente.HORA_INICIO
    WHERE mh.MATRICULA_ID = p_matricula_id;
END$$

CREATE PROCEDURE REGISTRAR_MATRICULA_HORARIO_VALIDADO(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED,
    OUT p_resultado INT
)
BEGIN
    DECLARE v_cupo_maximo INT DEFAULT 0;
    DECLARE v_matriculados INT DEFAULT 0;
    DECLARE v_conflictos INT DEFAULT 0;
    DECLARE v_duplicado INT DEFAULT 0;

    SELECT COUNT(*)
    INTO v_duplicado
    FROM UNI_MATRICULAS_HORARIOS
    WHERE MATRICULA_ID = p_matricula_id
      AND HORARIO_CURSO_ID = p_horario_curso_id;

    IF v_duplicado > 0 THEN
        SET p_resultado = -1; -- Ya existe la matrícula en ese horario.
    ELSE
        SELECT CUPO_MAXIMO
        INTO v_cupo_maximo
        FROM UNI_HORARIOS_CURSO
        WHERE HORARIO_CURSO_ID = p_horario_curso_id;

        SELECT COUNT(*)
        INTO v_matriculados
        FROM UNI_MATRICULAS_HORARIOS
        WHERE HORARIO_CURSO_ID = p_horario_curso_id;

        IF v_matriculados >= v_cupo_maximo THEN
            SET p_resultado = -2; -- Cupo máximo alcanzado.
        ELSE
            CALL EXISTE_CONFLICTO_HORARIO(p_matricula_id, p_horario_curso_id, v_conflictos);

            IF v_conflictos > 0 THEN
                SET p_resultado = -3; -- Conflicto de horario.
            ELSE
                INSERT INTO UNI_MATRICULAS_HORARIOS (MATRICULA_ID, HORARIO_CURSO_ID, FECHA_REGISTRO)
                VALUES (p_matricula_id, p_horario_curso_id, CURRENT_TIMESTAMP);
                SET p_resultado = 1;
            END IF;
        END IF;
    END IF;
END$$

CREATE PROCEDURE CALCULAR_PROMEDIO_FINAL(
    IN p_matricula_id BIGINT UNSIGNED,
    IN p_horario_curso_id BIGINT UNSIGNED,
    OUT p_promedio DECIMAL(5,2)
)
BEGIN
    SELECT COALESCE(SUM(n.CALIFICACION * e.PESO / 100), 0)
    INTO p_promedio
    FROM UNI_NOTAS n
    INNER JOIN UNI_EVALUACIONES e ON e.EVALUACION_ID = n.EVALUACION_ID
    WHERE n.MATRICULA_ID = p_matricula_id
      AND n.HORARIO_CURSO_ID = p_horario_curso_id;
END$$

DELIMITER ;
